[package]
name = "gaia"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@ulysse.io>"]

[dependencies]
byteorder = "1"
camera_controllers = "0.21"
gfx = "0.16"
image = "0.13"
piston = "0.32"
piston_window = "0.66"
pistoncore-sdl2_window = "0.42.0"
piston3d-cam = "0.3"
time = "0.1"
vecmath = "0.3"
