[package]
name = "gaia"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@ulysse.io>"]

[dependencies]
byteorder = "1"
error-chain = "0.10"
fps_counter = "0.2"
gfx = "0.16"
image = "0.13"
piston = "0.32"
piston3d-cam = "0.3"
piston_window = "0.66"
vecmath = "0.3"
